### ISSUE TITLE
¿qué esquema deberíamos usar para los nombres de los componentes?

### ISSUE THREAD

**Issue by rodowi** [mxabierto/componentes#3]
por ejemplo, ahorita mxabierto-header, creo que debería ser algo como dgm-navbar (ver #1)

sin saber del mundo de web components, me atrevo a decir que de alguna manera deberíamos encontrar un naming scheme, p. ej. {{domain}}-{{element}}

¿qué opinan?

**Comment by chuckcfs** [comment]
si, yo ahorita le puse mxabierto por el repo, pero si no, ¿cómo?

creo que me late {{domain}}-{{element}}

tons en el caso del header de datos sería, `datos-gob-header`??

**Comment by carlosmaya** [comment]
me quedo con lo de `<{domain}-{element}>` => `dgm-header`
